"""Candidate conferences not in the original spreadsheet. Websites are best
guesses that the crawler verifies; dates get filled from aggregator feeds."""
import json

N = []
def add(slug, name, website, city=None, region=None, country="US", type_="hacker", month=None, desc=None, notes=None, aliases=None, priority="normal", archived=0):
    N.append({"slug": slug, "name": name, "website": website, "city": city, "region": region, "country": country, "type": type_,
              "typical_month": month, "description": desc, "notes": notes, "aliases": aliases or [], "priority": priority, "archived": archived,
              "source": "research 2026-09"})

# --- BSides in the US/Canada that are on the bsides.org calendar but not in the sheet
add("bsides-denver", "BSides Denver", "https://www.bsidesden.org/", "Denver", "CO", month=9, type_="bsides")
add("bsides-houston", "BSides Houston", "https://www.bsideshou.org/", "Houston", "TX", month=9, type_="bsides")
add("bsides-cache", "BSides Cache", "https://www.bsidescache.org/", "Logan", "UT", month=9, type_="bsides", aliases=["BSidesCache"])
add("bsides-albuquerque", "BSides Albuquerque", "https://bsidesabq.org/", "Albuquerque", "NM", month=9, type_="bsides", aliases=["BSidesABQ"])
add("bsides-vi", "BSides Vancouver Island", "https://bsidesvi.ca/", "Victoria", "BC", "CA", month=9, type_="bsides", aliases=["BSidesVI"])
add("bsides-orlando", "BSides Orlando", "https://bsidesorlando.org/", "Orlando", "FL", month=9, type_="bsides")
add("bsides-cleveland", "BSides Cleveland", "https://bsidescle.com/", "Cleveland", "OH", month=9, type_="bsides", aliases=["BSidesCLE"])
add("bsides-saskatoon", "BSides Saskatoon", "https://bsidessaskatoon.ca/", "Saskatoon", "SK", "CA", month=9, type_="bsides")
add("bsides-bloomington", "BSides Bloomington", "https://bsidesbloomington.org/", "Bloomington", "IN", month=10, type_="bsides")
add("bsides-memphis", "BSides Memphis", "https://www.bsidesmemphis.org/", "Memphis", "TN", month=10, type_="bsides")
add("bsides-toronto", "BSides Toronto", "https://bsidesto.ca/", "Toronto", "ON", "CA", month=10, type_="bsides")
add("bsides-hampton-roads", "BSides Hampton Roads", "https://bsideshr.org/", "Norfolk", "VA", month=10, type_="bsides", aliases=["BSidesHamptonRoads"])
add("bsides-peoria", "BSides Peoria", "https://bsidespeoria.org/", "Peoria", "IL", month=10, type_="bsides")
add("bsides-cambridge-ma", "BSides Cambridge MA", "https://bsidescambridgema.org/", "Somerville", "MA", month=10, type_="bsides", aliases=["BSidesCambridgeMA", "BSides CambridgeMA"])
add("bsides-fredericton", "BSides Fredericton", "https://bsidesfredericton.ca/", "Fredericton", "NB", "CA", month=10, type_="bsides")
add("bsides-nova", "BSides NoVA", "https://bsidesnova.org/", "Arlington", "VA", month=10, type_="bsides", aliases=["BSidesNoVA"])
add("bsides-columbus", "BSides Columbus", "https://bsidescmh.org/", "Columbus", "OH", month=11, type_="bsides", aliases=["BSidesCMH"])
add("bsides-dfw", "BSides DFW", "https://bsidesdfw.com/", "Dallas", "TX", month=11, type_="bsides", aliases=["BSidesDFW"])
add("bsides-flood-city", "BSides Flood City", "https://bsidesfloodcity.org/", "Johnstown", "PA", month=11, type_="bsides")
add("bsides-rdu", "BSides RDU", "https://bsidesrdu.org/", "Raleigh", "NC", month=12, type_="bsides", aliases=["BSidesRDU"])
add("bsides-st-pete", "BSides St. Pete", "https://bsidesstpete.org/", "St. Petersburg", "FL", month=1, type_="bsides", aliases=["BSidesStPete"])
add("bsides-jacksonville", "BSides Jacksonville", "https://bsidesjax.org/", "Jacksonville", "FL", month=2, type_="bsides", aliases=["BSidesJAX"])
add("bsides-space-coast", "BSides Space Coast", "https://bsidesspacecoast.org/", "Melbourne", "FL", month=3, type_="bsides")
add("bsides-sgf", "BSides SGF", "https://bsidessgf.org/", "Springfield", "MO", month=3, type_="bsides", aliases=["BSidesSGF (Springfield, MO, USA)", "BSides Springfield"])
add("bsides-idaho-falls", "BSides Idaho Falls", "https://bsidesidahofalls.org/", "Idaho Falls", "ID", month=4, type_="bsides")
add("bsides-red-rocks", "BSides Red Rocks", "https://www.bsidesredrocks.org/", "St. George", "UT", month=11, type_="bsides", aliases=["BSidesRedRocks"])
add("bsides-st-johns", "BSides St. John's", "https://bsidesstjohns.ca/", "St. John's", "NL", "CA", month=9, type_="bsides")
# --- other BSides that usually run but had no upcoming listing yet
add("bsides-vancouver", "BSides Vancouver", "https://bsidesvancouver.com/", "Vancouver", "BC", "CA", type_="bsides")
add("bsides-calgary", "BSides Calgary", "https://www.bsidescalgary.org/", "Calgary", "AB", "CA", type_="bsides")
add("bsides-winnipeg", "BSides Winnipeg", "https://bsideswpg.ca/", "Winnipeg", "MB", "CA", type_="bsides")
add("bsides-halifax", "BSides Halifax", "https://bsideshalifax.ca/", "Halifax", "NS", "CA", type_="bsides")
add("bsides-boston", "BSides Boston", "https://bsidesboston.org/", "Boston", "MA", type_="bsides")
add("bsides-ri", "BSides Rhode Island", "https://bsidesri.org/", "Providence", "RI", type_="bsides", aliases=["BSidesRI"])
add("bsides-nh", "BSides New Hampshire", "https://bsidesnh.org/", "Manchester", "NH", type_="bsides", aliases=["BSidesNH"])
add("bsides-pittsburgh", "BSides Pittsburgh", "https://bsidespgh.com/", "Pittsburgh", "PA", type_="bsides", aliases=["BSidesPGH"])
add("bsides-indy", "BSides Indy", "https://bsidesindy.org/", "Indianapolis", "IN", type_="bsides")
add("bsides-austin", "BSides Austin", "https://bsidesaustin.com/", "Austin", "TX", type_="bsides")
add("bsides-huntsville", "BSides Huntsville", "https://bsideshuntsville.org/", "Huntsville", "AL", type_="bsides")
add("bsides-greenville", "BSides Greenville", "https://bsidesgvl.org/", "Greenville", "SC", type_="bsides", aliases=["BSidesGVL"])
add("bsides-asheville", "BSides Asheville", "https://bsidesasheville.com/", "Asheville", "NC", type_="bsides")
add("bsides-la", "BSides Los Angeles", "https://bsidesla.org/", "Los Angeles", "CA", type_="bsides", aliases=["BSidesLA"])
add("bsides-sacramento", "BSides Sacramento", "https://bsidessac.org/", "Sacramento", "CA", type_="bsides")
add("bsides-dc", "BSides DC", "https://bsidesdc.org/", "Washington", "DC", type_="bsides", aliases=["BSidesDC"])
add("bsides-long-island", "BSides Long Island", "https://bsidesli.org/", "Long Island", "NY", type_="bsides")
add("bsides-st-louis", "BSides St. Louis", "https://bsidesstl.org/", "St. Louis", "MO", type_="bsides", aliases=["BSidesSTL"])
add("bsides-iowa", "BSides Iowa", "https://bsidesiowa.org/", "Des Moines", "IA", type_="bsides")
add("bsides-boise", "BSides Boise", "https://bsidesboise.org/", "Boise", "ID", type_="bsides")
add("bsides-spokane", "BSides Spokane", "https://bsidesspokane.org/", "Spokane", "WA", type_="bsides")
add("bsides-santa-fe", "BSides Santa Fe", "https://bsidessantafe.org/", "Santa Fe", "NM", type_="bsides")
add("bsides-lehigh-valley", "BSides Lehigh Valley", "https://bsideslehighvalley.org/", "Bethlehem", "PA", type_="bsides")
# --- hacker / community cons in the US & Canada
add("shellcon", "ShellCon", "https://shellcon.io/", "Los Angeles", "CA", month=10)
add("toorcon", "ToorCon", "https://toorcon.net/", "San Diego", "CA", month=9)
add("texas-cyber-summit", "Texas Cyber Summit", "https://texascyber.com/", "Austin", "TX", month=9)
add("houseccon", "HOU.SEC.CON", "https://houstonseccon.com/", "Houston", "TX", month=10, aliases=["HouSecCon"])
add("wwhf-deadwood", "Wild West Hackin' Fest — Deadwood", "https://wildwesthackinfest.com/", "Deadwood", "SD", month=10, aliases=["Wild West Hackin' Fest Deadwood"])
add("hack-red-con", "Hack Red Con", "https://hackredcon.com/", "Louisville", "KY", month=12)
add("guildcon", "GuildCon", "https://guildcon.hackersguildpgh.com/", "Pittsburgh", "PA", month=11)
add("triss", "TRISS (Three Rivers Information Security Symposium)", "https://www.threeriversinfosec.com/", "Pittsburgh", "PA", month=10, aliases=["TRISS", "Three Rivers Information Security Symposium"])
add("burning-river-cyber-con", "Burning River Cyber Con", "https://burningrivercybercon.com/", "Cleveland", "OH", month=11)
add("threatcon1", "ThreatCon1", "https://www.threatcon1.org/", "Reston", "VA", month=10)
add("hackfest", "Hackfest", "https://hackfest.ca/", "Quebec City", "QC", "CA", month=10)
add("sector", "SecTor", "https://www.blackhat.com/sector/", "Toronto", "ON", "CA", type_="industry", month=10)
add("atlseccon", "AtlSecCon", "https://atlseccon.com/", "Halifax", "NS", "CA", month=4)
add("cansecwest", "CanSecWest", "https://www.secwest.net/", "Vancouver", "BC", "CA", month=9)
add("recon", "REcon", "https://recon.cx/", "Montreal", "QC", "CA", month=6, desc="Reverse engineering conference")
add("summercon", "Summercon", "https://www.summercon.org/", "New York", "NY", month=7)
add("hackaday-supercon", "Hackaday Supercon", "https://hackaday.io/superconference/", "Pasadena", "CA", type_="hardware", month=11, desc="Hackaday's hardware-hacker conference; badge hacking, talks, workshops", priority="high")
add("teardown", "Teardown (Crowd Supply)", "https://www.crowdsupply.com/teardown", "Portland", "OR", type_="hardware", month=6, desc="Crowd Supply's open hardware festival", priority="high")
add("vcf-east", "Vintage Computer Festival East", "https://vcfed.org/events/vintage-computer-festival-east/", "Wall", "NJ", type_="hardware", month=4, desc="VCF East at InfoAge, Wall NJ — vendor hall, workshops, exhibits", aliases=["VCF East"], priority="high")
add("vcf-midwest", "Vintage Computer Festival Midwest", "https://vcfmw.org/", "Schaumburg", "IL", type_="hardware", month=9, aliases=["VCF Midwest"])
add("vcf-west", "Vintage Computer Festival West", "https://vcfed.org/events/vintage-computer-festival-west/", "Mountain View", "CA", type_="hardware", month=8, aliases=["VCF West"])
add("vcf-southwest", "Vintage Computer Festival Southwest", "https://www.vcfsw.org/", "Dallas", "TX", type_="hardware", month=6, aliases=["VCF Southwest"])
add("vcf-southeast", "Vintage Computer Festival Southeast", "https://vcfsoutheast.org/", "Atlanta", "GA", type_="hardware", month=4, aliases=["VCF Southeast"])
add("open-hardware-summit", "Open Hardware Summit", "https://2026.oshwa.org/", None, None, type_="hardware", month=5, desc="OSHWA's annual summit; location changes yearly")
add("circle-city-con", "CircleCityCon", "https://circlecitycon.org/", "Indianapolis", "IN", month=6)
add("hackers-teaching-hackers", "Hackers Teaching Hackers", "https://hackersteachinghackers.com/", "Columbus", "OH", month=10)
add("shmoocon", "ShmooCon", "https://www.shmoocon.org/", "Washington", "DC", month=1, notes="ShmooCon held its final event in January 2025.", priority="ignore", archived=1)
add("hacker-halted", "Hacker Halted", "https://www.hackerhalted.com/", "Atlanta", "GA", type_="industry", month=10)
add("simply-cyber-con", "Simply Cyber Con", "https://simplycyber.io/", None, None, type_="online", month=11)
add("apres-cyber-slopes", "Aprés-Cyber Slopes Summit", "https://www.aprescyber.com/", "Park City", "UT", month=2)
add("attackcon", "ATT&CKcon", "https://attack.mitre.org/resources/attackcon/", "McLean", "VA", type_="industry", month=10)
add("defcon-franklin", "DEF CON Franklin", "https://defconfranklin.com/", None, None, type_="hacker", notes="Volunteer program, not a con; listed for reference", priority="low")
# --- maker / hardware adjacent, Philly-friendly
add("maker-faire-coney-island", "Maker Faire Coney Island", "https://coneyisland.makerfaire.com/", "Brooklyn", "NY", type_="maker", month=9)
add("maker-faire-rochester", "Maker Faire Rochester", "https://rochester.makerfaire.com/", "Rochester", "NY", type_="maker", month=11)
add("maker-faire-orlando", "Maker Faire Orlando", "https://www.makerfaireorlando.com/", "Orlando", "FL", type_="maker", month=11)
add("maker-faire-louisville", "Maker Faire Louisville", "https://louisville.makerfaire.com/", "Louisville", "KY", type_="maker", month=10)
add("maker-faire-baton-rouge", "Maker Faire Baton Rouge", "https://batonrouge.makerfaire.com/", "Baton Rouge", "LA", type_="maker", month=10)
add("maker-faire-fort-worth", "Maker Faire Fort Worth", "https://fortworth.makerfaire.com/", "Fort Worth", "TX", type_="maker", month=11)
add("maker-faire-meridian", "Maker Faire Meridian", "https://meridian.makerfaire.com/", "Meridian", "MS", type_="maker", month=8)
add("maker-faire-brownsville", "Maker Faire Brownsville", "https://www.btxspacefest.com/makerfaire", "Brownsville", "TX", type_="maker", month=9)
add("maker-faire-waterloo", "Maker Faire Waterloo", "https://www.waterloomakerfaire.org/", "Waterloo", "ON", "CA", type_="maker", month=9)
add("maker-faire-buffalo", "Maker Faire Buffalo", "https://buffalo.makerfaire.com/", "Buffalo", "NY", type_="maker", month=9)
# --- notable international (the ones worth a flight)
add("ccc-congress", "Chaos Communication Congress (39C3)", "https://events.ccc.de/", "Hamburg", None, "DE", type_="hacker", month=12, desc="CCC's annual congress, Dec 27-30", aliases=["39C3", "40C3", "CCC Congress"])
add("ccc-camp", "Chaos Communication Camp", "https://events.ccc.de/camp/", "Mildenberg", None, "DE", type_="camp", month=8, notes="Every four years; next expected August 2027.")
add("hardwear-io-nl", "Hardwear.io Netherlands", "https://hardwear.io/", "Amsterdam", None, "NL", type_="hardware", month=10)
add("brucon", "BruCON", "https://www.brucon.org/", "Mechelen", None, "BE", month=9)
add("troopers", "TROOPERS", "https://troopers.de/", "Heidelberg", None, "DE", month=6)
add("44con", "44CON", "https://44con.com/", "London", None, "GB", month=9)
add("lehack", "leHACK", "https://lehack.org/", "Paris", None, "FR", month=7)
add("nullcon-goa", "Nullcon Goa", "https://nullcon.net/", "Goa", None, "IN", month=2)
add("insomnihack", "Insomni'hack", "https://insomnihack.ch/", "Lausanne", None, "CH", month=2)
add("deepsec", "DeepSec", "https://deepsec.net/", "Vienna", None, "AT", month=11)
add("hexacon", "Hexacon", "https://hexacon.fr/", "Paris", None, "FR", month=10)
add("bornhack", "BornHack", "https://bornhack.dk/", "Gedser", None, "DK", type_="camp", month=8)
add("emf-camp", "Electromagnetic Field (EMF)", "https://www.emfcamp.org/", "Eastnor", None, "GB", type_="camp", month=6, notes="Biennial; 2026 edition happened, next expected 2028.")
add("ekoparty", "Ekoparty", "https://ekoparty.org/", "Buenos Aires", None, "AR", month=11)
add("black-hat-europe", "Black Hat Europe", "https://www.blackhat.com/", "London", None, "GB", type_="industry", month=12)
add("hitb", "Hack In The Box (HITB)", "https://conference.hitb.org/", "Amsterdam", None, "NL", month=4)
add("steelcon", "SteelCon", "https://www.steelcon.info/", "Sheffield", None, "GB", month=7)
add("bsides-vegas-placeholder", "", "", archived=1)  # removed below
N = [n for n in N if n["name"]]
json.dump(N, open("research/new_conferences.json", "w"), indent=1)
print(len(N), "new candidates")
